Просмотр деталей пользователя
STC12-team/BookSharingProject pull request #121
Opened 2018-11-05 15:21 UTC by artemzi

Работает, согласно ожиданиям.

Остались TODO, которые нужно будет дорабатывать по мере закрытия следующих задач.

Тесты хотелось бы улучшить.

Close #86

2018-11-05 17:06 UTC, shagiev requested changes

2018-11-05 17:06 UTC, shagiev commented on src/main/db/base/2018-11-05-create-user-details-table.xml
> +                                 deferrable="true"
По-моему, deferrable не стоит ставить и initiallyDeferred

2018-11-05 17:06 UTC, shagiev commented on src/main/db/base/2018-11-05-update-users-table-email-column.xml
> +        <!-- TODO set nullable to false after registration process will be fixed with adding new fields -->
В чейнджсете не стоит оставлять todo комментарий. Потому что когда его будешь изменять, вроде как хэш изменится

2018-11-05 17:06 UTC, shagiev commented on src/main/java/ru/innopolis/stc12/booksharing/controller/ProfileController.java
> +    @ExceptionHandler(TestException.class)
Давай использовать нормальные осмысленные эксепшены уже.

2018-11-05 17:06 UTC, shagiev commented on src/main/java/ru/innopolis/stc12/booksharing/model/dao/UserDaoImpl.java
> +    private static org.springframework.security.core.userdetails.User currentUserDetails(){
Хочется более понятное имя метода.

2018-11-05 17:06 UTC, shagiev commented on src/main/java/ru/innopolis/stc12/booksharing/model/dao/UserDaoImpl.java
> +    private static org.springframework.security.core.userdetails.User currentUserDetails(){
get...?

2018-11-05 17:14 UTC, artemzi commented on src/main/db/base/2018-11-05-update-users-table-email-column.xml
> +        <!-- TODO set nullable to false after registration process will be fixed with adding new fields -->
@shagiev done

2018-11-05 17:14 UTC, artemzi commented on src/main/java/ru/innopolis/stc12/booksharing/controller/ProfileController.java
> +    @ExceptionHandler(TestException.class)
@shagiev done

2018-11-05 17:16 UTC, artemzi commented on src/main/java/ru/innopolis/stc12/booksharing/model/dao/UserDaoImpl.java
> +    private static org.springframework.security.core.userdetails.User currentUserDetails(){
@shagiev этот метод не возвращает детали, getUserDetails возвращает детали текущего пользователя, а тут используется класс из spring security. Тут есть проблема с именованием, поскольку User и UserDetails существуют в различных пакетах и резолвится она пока указанием полного имени пакета.

2018-11-05 17:21 UTC, artemzi commented on src/main/java/ru/innopolis/stc12/booksharing/model/dao/UserDaoImpl.java
> +    private static org.springframework.security.core.userdetails.User currentUserDetails(){
@shagiev done

2018-11-05 17:23 UTC, bass-2000 submitted a review, later dismissed

2018-11-05 17:28 UTC, artemzi commented on src/main/db/base/2018-11-05-create-user-details-table.xml
> +                                 deferrable="true"
Done

2018-11-06 12:41 UTC, shagiev approved these changes

2018-11-06 13:06 UTC, svdovin approved these changes

2018-11-06 13:06 UTC, merged