Feature/issue 123
STC12-team/BookSharingProject pull request #134
Opened 2018-11-09 15:20 UTC by rmunirov

Пока лучше не мержить, на согласование страницы просмотра книги.

2018-11-09 18:41 UTC, shagiev requested changes

2018-11-09 18:41 UTC, shagiev commented on src/main/webapp/WEB-INF/pages/library.jsp
> +                                        <a href="/bookEditionDesc?bookEditionId=${bookEdition.id}">
По-моему, это уродство. Можно же просто /bookEditionDesc/${bookEdition.id}

2018-11-09 18:41 UTC, shagiev commented on src/main/webapp/WEB-INF/tags/bookdescription.tag
> +            </div>
Тут один из двух вариантов - или количество свободных книг или количество человек в очереди

2018-11-09 18:41 UTC, shagiev commented on src/main/webapp/WEB-INF/tags/bookdescription.tag
> +            </div>
Но хотя сейчас можно оставить оба пока

2018-11-09 18:41 UTC, shagiev commented on src/main/java/ru/innopolis/stc12/booksharing/controller/BookEditionsController.java
> +    private BookQueueService bookQueueService;
Я думаю, что если нам нужно 4 сервиса, то это перегруженный контроллер. Надо или создавать более специализированные сервисы для нужд в этом контроллере, или делить контроллер на два

2018-11-09 18:41 UTC, shagiev commented on src/main/java/ru/innopolis/stc12/booksharing/controller/BookEditionsController.java
> +        int countBookCopyIsStatusFree = bookCopiesService.getBookCopyCountByBookEditionIdInStatusFree(id);
freeBookCopiesCount будет лучше, мне кажется

2018-11-09 18:41 UTC, shagiev commented on src/main/java/ru/innopolis/stc12/booksharing/controller/BookEditionsController.java
> +        int countBookCopyIsStatusFree = bookCopiesService.getBookCopyCountByBookEditionIdInStatusFree(id);
ну или Is заменить на In

2018-11-11 19:33 UTC, shagiev submitted a review, later dismissed

2018-11-12 08:56 UTC, shagiev approved these changes

2018-11-12 09:06 UTC, artemzi approved these changes

2018-11-12 09:06 UTC, merged