Feature/issue 73
STC12-team/BookSharingProject pull request #135
Opened 2018-11-09 15:48 UTC by bass-2000

fixed bug with search by isbn

2018-11-09 17:32 UTC, svdovin requested changes

2018-11-09 17:32 UTC, svdovin commented on src/main/java/ru/innopolis/stc12/booksharing/utils/RegexMatcher.java
> +    public static String getStringByRegexp(String regexp, String inputString) {
Теста нет? 
Не понятно что ожидается от этого метода.
Если первая попавшаяся группа, то получается, что строка не вся ищется? 
Например, по шаблону [123] есть два вхождения в строку 123ччч123.

2018-11-09 17:36 UTC, artemzi requested changes

2018-11-09 17:36 UTC, artemzi commented on src/main/java/ru/innopolis/stc12/booksharing/controller/LibraryController.java
> +            if (bookEdition != null) {
не понял этой части `bookEditionList `, он же не null там новый `ArrayList` создается при каждом вызове, зачем проверка и зачем в null ставить?

тут явно дополнительная проблема с тестом будет и судя по тесту контроллера эта часть (условия) не тестируется совсем

2018-11-09 17:48 UTC, bass-2000 commented on src/main/java/ru/innopolis/stc12/booksharing/utils/RegexMatcher.java
> +    public static String getStringByRegexp(String regexp, String inputString) {
ищет фул мэтч

2018-11-09 17:49 UTC, bass-2000 commented on src/main/java/ru/innopolis/stc12/booksharing/controller/LibraryController.java
> +            if (bookEdition != null) {
public BookEdition getBookEditionByIsbn(String isbn) {
        //TODO если передать ISBN, которого нет в базе, вылетает исключение
        return jdbcTemplate.queryForObject(SQL_SELECT_BY_ISBN, new Object[]{isbn}, new BookEditionMapper());
        BookEdition bookEdition;
        try {
            bookEdition = jdbcTemplate.queryForObject(SQL_SELECT_BY_ISBN, new Object[]{isbn}, new BookEditionMapper());
        } catch (DataAccessException daException) {
            logger.debug("BookEdition not found by isbn: " + isbn);
            return null;
        }
        return bookEdition;

2018-11-09 17:54 UTC, artemzi commented on src/main/java/ru/innopolis/stc12/booksharing/controller/LibraryController.java
> +            if (bookEdition != null) {
@bass-2000 это наверно что -то объясняет, но я почему -то опять не понял. Если речь о исключении, да там NullPointer вроде его тоже перехватить в том же блоке catch можно же.

2018-11-09 18:03 UTC, bass-2000 commented on src/main/java/ru/innopolis/stc12/booksharing/controller/LibraryController.java
> +            if (bookEdition != null) {
мы возвращаем null в случае если не нашли книг (обернуто все в трай-кетч, но ретурн идет из кетч), и в сервисе просто пробрасываем в контроллер полученный null, а вот в контроллере мы смотрим, если не нал - всовываем в лист, потому как на странице library мы обрабатываем именно лист в jsp

2018-11-09 18:19 UTC, artemzi submitted a review, later dismissed

2018-11-09 18:19 UTC, artemzi commented on src/main/java/ru/innopolis/stc12/booksharing/controller/LibraryController.java
> +            if (bookEdition != null) {
@bass-2000 Так метод null возвращающий ты привел `getBookEditionByIsbn` , а используешь `getAllBookEditions`, что совсем странно, потому как сколько там этих изданий ? Может список вообще быть пустым и может ли он миллион записей вернуть? Но в принципе если тебе там нужна такая проверка на null и ты это делаешь столько if / else сознательно -ок, тебе это тестировать :)

2018-11-09 18:21 UTC, svdovin requested changes

2018-11-09 18:21 UTC, svdovin commented on src/main/java/ru/innopolis/stc12/booksharing/controller/BookCopiesController.java
> +    private static final String REGEXP_ISBN = "(ISBN[-]*(1[03])*[ ]*(: ){0,1})*(([0-9Xx][- ]*){13}|([0-9Xx][- ]*){10})";
Если фулмач выдаст вместе с ISBN и вместе с тире, то надо потом удалять эти символы перед вставкой в запрос. У нас же будет храниться неформатированная строка в БД?

2018-11-09 18:24 UTC, shagiev commented on src/main/java/ru/innopolis/stc12/booksharing/controller/BookCopiesController.java
> +    private static final String REGEXP_ISBN = "(ISBN[-]*(1[03])*[ ]*(: ){0,1})*(([0-9Xx][- ]*){13}|([0-9Xx][- ]*){10})";
Ну вот вообще не в контроллере этому место. Как и другой логике

2018-11-09 18:24 UTC, shagiev commented on src/main/java/ru/innopolis/stc12/booksharing/controller/BookCopiesController.java
> +        else {
Теоритически название книги может подходить под ISBN. 1984?

2018-11-09 18:24 UTC, shagiev commented on src/main/java/ru/innopolis/stc12/booksharing/utils/RegexMatcher.java
> +    public static String getStringByRegexp(String regexp, String inputString) {
вот тут точно надо javadoc

2018-11-09 19:18 UTC, svdovin commented on src/main/java/ru/innopolis/stc12/booksharing/controller/BookCopiesController.java
> +        else {
наверно тут надо так: если найдется ISBN, то добавлять в запрос where OR для ISBNа:

псевдокод:
sql = 'select * from books where name = inputstring';
if (!RegexMatcher.getStringByRegexp(REGEXP_ISBN, typeValue).equals("")) {
            sql = sql + ' OR isbn = inputstring';
        }

execute(sql);

2018-11-09 19:37 UTC, svdovin commented on src/main/java/ru/innopolis/stc12/booksharing/utils/RegexMatcher.java
> +    public static String getStringByRegexp(String regexp, String inputString) {
тест лучше всякого javadoc покажет как это использовать

2018-11-09 20:05 UTC, svdovin requested changes

2018-11-09 20:05 UTC, svdovin commented on src/main/java/ru/innopolis/stc12/booksharing/model/dao/BookEditionsDaoImpl.java
> +            logger.debug("BookEdition not found by author: " + publisher);
текст By Publisher, а не by author

2018-11-09 20:05 UTC, svdovin commented on src/test/java/ru/innopolis/stc12/booksharing/controller/BookCopiesControllerTest.java
> +        assertEquals("addBookByUser", bookCopiesController.searchBook("ISBN 978-3-642-11746-6", model));
1) тут наверно не anyString(), а 9783642117466 сразу проверять (хотя это лучше из контроллера в сервис ваще вынести)
2) здесь проверка страницы, а она всегда одинаковая. Надо изменение модели проверять - ложится туда объект или сообщение, что не найдено

2018-11-10 09:28 UTC, bass-2000 commented on src/main/java/ru/innopolis/stc12/booksharing/controller/BookCopiesController.java
> +    private static final String REGEXP_ISBN = "(ISBN[-]*(1[03])*[ ]*(: ){0,1})*(([0-9Xx][- ]*){13}|([0-9Xx][- ]*){10})";
ок, а где если не в контроллере? В сервисе?

2018-11-10 18:45 UTC, shagiev commented on src/main/java/ru/innopolis/stc12/booksharing/controller/BookCopiesController.java
> +    private static final String REGEXP_ISBN = "(ISBN[-]*(1[03])*[ ]*(: ){0,1})*(([0-9Xx][- ]*){13}|([0-9Xx][- ]*){10})";
Да, я имел в виду, что логику надо выносить в сервисы

2018-11-11 12:23 UTC, bass-2000 commented on src/main/java/ru/innopolis/stc12/booksharing/utils/RegexMatcher.java
> +    public static String getStringByRegexp(String regexp, String inputString) {
добавил и тест и джавадок

2018-11-11 12:24 UTC, bass-2000 commented on src/main/java/ru/innopolis/stc12/booksharing/controller/BookCopiesController.java
> +    private static final String REGEXP_ISBN = "(ISBN[-]*(1[03])*[ ]*(: ){0,1})*(([0-9Xx][- ]*){13}|([0-9Xx][- ]*){10})";
как договоримся по этому поводу и решим как у нас будет работать магический поиск - использую

2018-11-11 12:24 UTC, bass-2000 commented on src/main/java/ru/innopolis/stc12/booksharing/controller/BookCopiesController.java
> +    private static final String REGEXP_ISBN = "(ISBN[-]*(1[03])*[ ]*(: ){0,1})*(([0-9Xx][- ]*){13}|([0-9Xx][- ]*){10})";
ревертнул все до состояния девелопа и оставил как было

2018-11-11 12:25 UTC, bass-2000 commented on src/main/java/ru/innopolis/stc12/booksharing/model/dao/BookEditionsDaoImpl.java
> +            logger.debug("BookEdition not found by author: " + publisher);
исправил

2018-11-11 12:25 UTC, bass-2000 commented on src/test/java/ru/innopolis/stc12/booksharing/controller/BookCopiesControllerTest.java
> +        assertEquals("addBookByUser", bookCopiesController.searchBook("ISBN 978-3-642-11746-6", model));
какая разница когда метод дергается?

2018-11-12 19:02 UTC, svdovin submitted a review, later dismissed

2018-11-12 19:30 UTC, svdovin approved these changes

2018-11-12 19:31 UTC, artemzi approved these changes

2018-11-12 19:32 UTC, merged