Bugfix/issue 139
STC12-team/BookSharingProject pull request #142
Opened 2018-11-13 09:26 UTC by rmunirov

Добавил авторизацию через форму в главном меню.

2018-11-13 09:50 UTC, bass-2000 requested changes

2018-11-13 09:50 UTC, bass-2000 commented on src/main/java/ru/innopolis/stc12/booksharing/controller/BookCopiesController.java
> +    //private static final String REGEXP_ISBN = "(ISBN[-]*(1[03])*[ ]*(: ){0,1})*(([0-9Xx][- ]*){13}|([0-9Xx][- ]*){10})";
можно удалить

2018-11-13 09:50 UTC, bass-2000 commented on src/main/java/ru/innopolis/stc12/booksharing/controller/LoginController.java
> +            //model.addAttribute("loginError", error);
лучше удалить

2018-11-13 09:50 UTC, bass-2000 commented on src/main/webapp/WEB-INF/web.xml
> +        <location>/WEB-INF/pages/error404.jsp</location>
мб не в каталог pages класть эрроры? а создать подкаталог под эти нужды?

2018-11-13 09:56 UTC, rmunirov commented on src/main/webapp/WEB-INF/web.xml
> +        <location>/WEB-INF/pages/error404.jsp</location>
До этого они лежали в корне webapp, но spring не мог найти exception.jsp при возникновении исключения.

2018-11-13 20:01 UTC, artemzi approved these changes

2018-11-13 20:01 UTC, artemzi commented on src/main/java/ru/innopolis/stc12/booksharing/controller/LoginController.java
> +            throw new ControllerException("Введены неверный пароль или логин!");
Если уже запросили изменения в пулреквесте, то может начать строки выносить в properties ?

2018-11-14 18:20 UTC, bass-2000 approved these changes

2018-11-14 18:20 UTC, merged