Looks like add hibernate support
STC12-team/BookSharingProject pull request #157
Opened 2018-11-16 10:25 UTC by artemzi

Hibernate прикручен

2018-11-16 15:19 UTC, svdovin requested changes

2018-11-16 15:19 UTC, svdovin commented on src/main/webapp/WEB-INF/database-context.xml
> +                    update
здесь надо validate, потому что обнавление будет делать ликвибейз , а не hibernate

2018-11-16 16:21 UTC, artemzi commented on src/main/webapp/WEB-INF/database-context.xml
> +                    update
@svdovin Done.

2018-11-16 16:25 UTC, svdovin approved these changes

2018-11-18 10:12 UTC, rmunirov approved these changes

2018-11-18 10:13 UTC, merged