Abstract Hibernate Dao
STC12-team/BookSharingProject pull request #173
Opened 2018-11-28 21:26 UTC by svdovin

2018-11-29 19:59 UTC, artemzi submitted a review, later dismissed

2018-11-30 11:59 UTC, bass-2000 commented on src/main/java/ru/innopolis/stc12/booksharing/controller/CatalogController.java
> +        List<BookCopy> bookCopies = bookCopiesService.getBookCopyByUser(0);
Почему одну отображаем книгу?

2018-11-30 12:00 UTC, bass-2000 commented on src/main/java/ru/innopolis/stc12/booksharing/model/dao/BookQueueDaoImpl.java
> +        return null;
почему null?

2018-11-30 12:01 UTC, bass-2000 commented on src/main/java/ru/innopolis/stc12/booksharing/model/dao/UserDao.java
> +    List<BookCopy> getBookCopyByUser(int userId);
точно тут надо а не в бук копи?

2018-11-30 12:01 UTC, bass-2000 commented on src/main/java/ru/innopolis/stc12/booksharing/model/dao/entity/BookCopy.java
> +    /*public BookCopy(int id, BookEdition bookEdition, User owner, BookCopiesStatus status) {
убрать комменты

2018-11-30 12:05 UTC, bass-2000 commented on src/main/java/ru/innopolis/stc12/booksharing/service/UserService.java
> +        return this.userDao.findAll();
не нравится мне название метода findAll. findAllWhat?

2018-11-30 12:06 UTC, bass-2000 requested changes
Работа проведена хорошая, но еще сыровато для мерджа

2018-12-01 09:18 UTC, svdovin commented on src/main/java/ru/innopolis/stc12/booksharing/controller/CatalogController.java
> +        List<BookCopy> bookCopies = bookCopiesService.getBookCopyByUser(0);
изменил на отображение всех книг по пользователю

2018-12-01 09:20 UTC, svdovin commented on src/main/java/ru/innopolis/stc12/booksharing/model/dao/BookQueueDaoImpl.java
> +        return null;
переделал на и перенос в сервисы

2018-12-01 09:21 UTC, svdovin commented on src/main/java/ru/innopolis/stc12/booksharing/model/dao/UserDao.java
> +    List<BookCopy> getBookCopyByUser(int userId);
перенес getBookCopiesByUser в сервисы

2018-12-01 09:22 UTC, svdovin commented on src/main/java/ru/innopolis/stc12/booksharing/service/UserService.java
> +        return this.userDao.findAll();
должно быть понятно из контекста - User. Этот метод обощен для джинериков

2018-12-02 07:42 UTC, avsharapov commented on src/main/java/ru/innopolis/stc12/booksharing/model/dao/AbstractDaoImp.java
> +    public CriteriaBuilder getCriteriaBuilder(){
В итоге этими методами пользуются только потомки? Если да то может спрятать их поставив модификатор protected.

2018-12-02 07:43 UTC, avsharapov commented on src/main/java/ru/innopolis/stc12/booksharing/model/dao/AbstractDaoImp.java
> +    public Root<T> getRoot() {
Тут тоже вопрос про protected.

2018-12-02 07:44 UTC, avsharapov commented on src/main/java/ru/innopolis/stc12/booksharing/model/dao/AbstractDaoImp.java
> +    public List<T> getListByPredicates(Predicate... args) {
И тут может protected.

2018-12-02 08:01 UTC, avsharapov commented on src/main/java/ru/innopolis/stc12/booksharing/model/dao/UserDaoImpl.java
> +        return (User)getCurrentSession()
Неожиданно.
А почему не 
 Predicate predicate = getCriteriaBuilder().equal(getRoot().get("login"), login);
 List<User> list = getListByPredicates(predicate);
 if (list.isEmpty()) { return null; }
 return list.get(0);

2018-12-02 08:04 UTC, avsharapov commented on src/main/java/ru/innopolis/stc12/booksharing/model/dao/entity/BookEdition.java
> +    private int id;
Книжек может быть очень много. Может id переделать на long. Да и в остальных случаях нужно подумать на будущее.

2018-12-02 08:10 UTC, avsharapov commented on src/main/java/ru/innopolis/stc12/booksharing/model/dao/entity/BookEdition.java
> +    @OneToOne
Это я неверно насоветовал. Тут не OneToOne а правильно было ManyToOne потому что много книг может содержать одного и того же издателя.

2018-12-02 08:12 UTC, avsharapov commented on src/main/java/ru/innopolis/stc12/booksharing/model/dao/entity/BookEdition.java
> +    @OneToOne
При ManyToOne тут будет не обязателен JoinColumn, он должен сам додуматься что по ключу связь.

2018-12-02 11:08 UTC, svdovin commented on src/main/java/ru/innopolis/stc12/booksharing/model/dao/AbstractDaoImp.java
> +    public CriteriaBuilder getCriteriaBuilder(){
исправил

2018-12-02 11:08 UTC, svdovin commented on src/main/java/ru/innopolis/stc12/booksharing/model/dao/AbstractDaoImp.java
> +    public Root<T> getRoot() {
исправил

2018-12-02 11:09 UTC, svdovin commented on src/main/java/ru/innopolis/stc12/booksharing/model/dao/AbstractDaoImp.java
> +    public List<T> getListByPredicates(Predicate... args) {
исправил

2018-12-02 11:16 UTC, svdovin commented on src/main/java/ru/innopolis/stc12/booksharing/model/dao/UserDaoImpl.java
> +        return (User)getCurrentSession()
Это я раньше сделал. У Раиля круче, исправил.

2018-12-02 11:49 UTC, svdovin commented on src/main/java/ru/innopolis/stc12/booksharing/model/dao/entity/BookEdition.java
> +    private int id;
переделал на long

2018-12-02 15:50 UTC, svdovin commented on src/main/java/ru/innopolis/stc12/booksharing/model/dao/entity/BookEdition.java
> +    @OneToOne
исправил на Many

2018-12-02 16:28 UTC, avsharapov approved these changes
Нужно доделать
1. Тесты
2. Сделать подход к получению данных единообразным.
3. Проверить связи у сущностей.

2018-12-02 16:30 UTC, bass-2000 approved these changes

2018-12-02 16:30 UTC, bass-2000 approved these changes

2018-12-02 16:31 UTC, artemzi approved these changes

2018-12-02 16:31 UTC, merged